version: '3'

services:
  app:
    image: laravel:11
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ptsmart
      - DB_USERNAME=ptsmart
      - DB_PASSWORD=ptsmart
    ports:
      - "80:80"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=80

  db:
    image: postgres:14
    container_name: ptsmart-db
    environment:
      POSTGRES_DB: ptsmart
      POSTGRES_USER: ptsmart
      POSTGRES_PASSWORD: ptsmart
    ports:
      - "6545:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
